### ISSUE TITLE
Search bar is broken

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-docs#105]
Reproduction steps:

Open docs with chrome, click on search bar, type something, hit enter, and nothing happens

**Comment by Unnvaldr** [comment]
Thanks for report, I'll look into it ASAP

**Comment by Unnvaldr** [comment]
I've reproduced it on ``Brave Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)``. Encountered only on first entrance in Private window mode. Fix is on its way

**Comment by Unnvaldr** [comment]
Fix integrated on production. Will take some time to propagate
