### ISSUE TITLE
CDN Link Generator shows wrong libnode links for linux release branch.

### ISSUE THREAD

**Issue by vicelo23** [altmp/altv-docs#107]
### Description of the problem

The CDN Link Generator shows libnode.so.102 for the release branch but currently libnode.so.83 is the latest libnode version for release branch.

### Reproduction steps

1. Go https://docs.altv.mp/articles/cdn_links.html
2. Select release as branch and x64_linux as OS.
3. Check js-module checkbox.
4. Click Generate Links button.
5. The given libnode CDN link is this: https://cdn.altv.mp/js-module/release/x64_linux/modules/js-module/libnode.so.102

### Expected behaviour

The given CDN link should be this instead: https://cdn.altv.mp/js-module/release/x64_linux/modules/js-module/libnode.so.83

### Operating system

-

### Version

-

**Comment by C0kkie** [comment]
Thats because dev already is changed to 102, not sure if i will add a branch check just for this, cuz we update node maybe once a year or something, so its not really worth

**Comment by vicelo23** [comment]
> Thats because dev already is changed to 102, not sure if i will add a branch check just for this, cuz we update node maybe once a year or something, so its not really worth

If you run `wget/curl https://cdn.altv.mp/js-module/release/x64_linux/modules/js-module/libnode.so.102` you will get 404 HTTP response because libnode.so.102 is not available in release branch. The peoples who are not aware of this bug are failing to get appropriate URL. As you said this might be fixed by itself when both dev and release branches have same libnode version but up to you.
