### ISSUE TITLE
[Safari] discord.js using unsupported lookbehind regex

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-docs#143]
Discord.js is failing due unsupported regex usage. Impact unknown as page is currently unusable with safari (#144)

![Error Message](https://user-images.githubusercontent.com/69921315/184500925-dedf09a3-5588-4d4a-99e7-91258b7c62fd.png)

**Comment by Unnvaldr** [comment]
Fixed in Unnvaldr/DiscordFx@8a701ed1ff587a46fab76c629e6fe01b7154b6c2. Needs testing.

**Comment by deluvas1911** [comment]
Fixed in 10db81ca
Tested on iOS & macOS 12.5
