### ISSUE TITLE
[Safari] Docs unresponsive / click events not working

### ISSUE THREAD

**Issue by deluvas1911** [altmp/altv-docs#144]
Most likely related due errors in docfx.js & discord.js (#143).
`#sidetoc` elements aren't rendered, navbar is in collapsed state and unresponsible to click

![Page Overview](https://user-images.githubusercontent.com/69921315/184500901-848b87e8-aaa0-40fa-bf59-503f8428c35f.png)

![Docfx.js Error](https://user-images.githubusercontent.com/69921315/184500911-fc3adec3-2540-4934-b81d-3f85493ba02e.png)

**Comment by Unnvaldr** [comment]
Fixed in Unnvaldr/DiscordFx@7303b7c0c8432470d6c29c5261d506f8c5df059a. Needs testing.

**Comment by deluvas1911** [comment]
Fixed in 10db81ca
Tested on iOS & macOS 12.5
