### ISSUE TITLE
client console

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-docs#15]
Port and update article about client console from wiki https://wiki.altv.mp/wiki/Scripting:Client_Console to docs.

**Comment by ThomasMarangoni** [comment]
add info about external console https://github.com/altmp/altv-issues/issues/1055#event-5258086144

**Comment by C0kkie** [comment]
Added https://github.com/altmp/altv-docs/commit/63ac9d439396f919bb1fb0e20b743537cefa956c
