### ISSUE TITLE
early auth system

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-docs#28]
port and update article early auth system from wiki https://wiki.altv.mp/wiki/Tutorial:Setup_EarlyAuth to docs

**Comment by ThomasMarangoni** [comment]
add https://github.com/altmp/altv-issues/issues/1121#issuecomment-921925611 to docs

**Comment by C0kkie** [comment]
Added https://github.com/altmp/altv-docs/commit/965027b7e077f893f616ac978652181aa9fa179c
