### ISSUE TITLE
weather

### ISSUE THREAD

**Issue by ThomasMarangoni** [altmp/altv-docs#61]
port article weather from wiki https://wiki.altv.mp/wiki/GTA:Weather to docs

**Comment by C0kkie** [comment]
Added

https://github.com/altmp/altv-docs-gta/commit/15d283af1cde6b397fb8d6abd35f720c8a9573e4
https://github.com/altmp/altv-docs-gta/commit/e51e4588aeb1467a54c7f0e6ce0b4f0c93f347d1
