### ISSUE TITLE
doc: beforeConnect

### ISSUE THREAD

**Issue by FabianTerhorst** [altmp/altv-docs#74]
beforeConnect is the event where servers can intercept the player connection for checking e.g. if player is banned.

**Comment by FabianTerhorst** [comment]
remember when you cancel the event you have to use plyer.kick. Otherwise undefined behavior happens.

**Comment by C0kkie** [comment]
https://github.com/altmp/altv-types/commit/c7d96ec3bcdd0e16ed27d3e9dd1b12f925a0ad89
