### ISSUE TITLE
rmlui docs article

### ISSUE THREAD

**Issue by C0kkie** [altmp/altv-docs#92]

**Comment by DurtyFree** [comment]
- Article in style of "Getting Started"
- How to draw something simple on the screen
- Mention style similar to working with html docs
- Mention RmlUI alt:V example repositories
- Mention API docs:
https://docs.altv.mp/js/api/alt-client.RmlElement.html
https://docs.altv.mp/js/api/alt-client.RmlDocument.html

**Comment by deluvas1911** [comment]
PR #134
